custom work
pion/ion-sdk-go pull request #35
Opened 2021-05-23 12:31 UTC by manishiitg

#### Description

#### Reference issue
Fixes #...

2021-05-23 14:06 UTC, adwpc commented on client.go
> +		log.Debugf("id=%v err=%v", c.uid, err)
I think log.Errorf is better, it's high level log

2021-05-23 17:26 UTC, leewardbound commented
I think it's a bad idea to commit so many large movie files to this repo. Please find a way to make this PR not include large, unnecessary video files, it will greatly increase the library size; alternatively, since this is just an "example", you could move the code and all the videos to an unrelated repository.

2021-05-23 17:35 UTC, leewardbound requested changes

2021-05-23 17:35 UTC, leewardbound commented on example/simple/main.go
> +	// c.OnTrack = saveToDisk
I think this shouldn't be commented out in this example :)

2021-05-23 17:35 UTC, leewardbound commented on example/track-to-rtp/README.md
> +export RTMP_URL=rtmp://bom01.contribute.live-video.net/app/live_666332364_5791UvimKkDZW8edq8DAi4011wc4cR
Did you intend to publish your stream key here?

2021-05-23 17:35 UTC, leewardbound commented on example/track-to-rtp/main.go
> +			if _, err = c.conn.Write(b[:n]); err != nil {
When I originally wrote this sample, I also copied this same block of code from `pion/webrtc/examples/rtp-forwarder` but that example is based off a JSFiddle approach and a CLI interaction - I don't believe this block of code belongs in this example anymore.

2021-05-23 17:35 UTC, leewardbound commented on example/ion-sfu-cluster-load-tool/README.md
> +## Ion-sfu load testing tool
Please update the README to reflect the purpose of the example, it is not clear what this example does, or why it's different than the other load tool example.

2021-05-23 17:35 UTC, leewardbound commented on example/mirror-sfu/README.md
> +# Simple
Please update the README to reflect the purpose of the example, it is not clear what this example does, and the README is from a different example.

2021-05-23 17:38 UTC, leewardbound commented
Thanks for your interest in helping with `ion-sdk-go`! I don't mean to be harsh but - In general, this PR adds a lot of small changes that I think would be better if you split up into smaller PRs that were more related - like changing `log.Error` to `log.Debug` without a good explanation/justification. Maybe those kinds of changes are appropriate, but they don't belong in one-big-lump PR together!

In my humble opinion, each Example you submit (or modify) should be its own PR.

2021-05-24 14:34 UTC, closed without merging

2021-05-24 14:35 UTC, manishiitg commented
@leewardbound i am sorry, this PR was submitted my mistakes. i didn't release this got submitted

2021-05-24 14:37 UTC, leewardbound commented
No worries, I am sorry if I came off tough, hope the feedback was helpful 😊

2021-05-24 14:39 UTC, manishiitg commented
yes. i submitted a new PR. that is genuine :) hope that helps